// 字段名英中映射：将后端 JSON key 转换为审核表格显示的中文标签

export const fieldNameMap: Record<string, string> = {
  plaintiff_branch_raw: '原告分公司（原文）',
  plaintiff_name_final: '原告名称',
  plaintiff_credit_code: '原告统一社会信用代码',
  plaintiff_person_in_charge: '原告负责人',
  plaintiff_address: '原告住址',
  plaintiff_phone: '原告电话',
  defendant_name: '被告名称',
  defendant_credit_code: '被告统一社会信用代码',
  defendant_legal_rep: '被告法定代表人',
  defendant_address: '被告住址',
  contacts: '联系人',
  contract_no: '合同编号',
  contract_title: '合同标题',
  contract_sign_date: '签约日期',
  elevator_qty: '台数（验收，写入起诉状）',
  elevator_qty_by_approval: '台数（审批表）',
  elevator_qty_by_contract: '台数（合同）',
  elevator_qty_by_acceptance: '台数（验收报告）',
  total_amount: '合同总价',
  paid_amount: '已付金额',
  unpaid_amount: '未付金额',
  amount_currency: '币种',
  acceptance_latest_date: '最晚验收日期',
  payment_clause_location: '付款条款位置',
  payment_clause_text: '付款条款原文',
  breach_interest_clause_location: '违约利率条款位置',
  breach_interest_rate_text: '违约利率',
  dispute_clause_location: '争议解决条款位置',
  dispute_clause_text: '争议解决条款内容',
  project_site: '工程地点',
  internet_lookup_status: '联网查询状态',
  interest_rate_basis: '逾期利息计算标准',
  court_district: '管辖法院（辖区）',
  contract_type: '合同类型',
  payment_clause_summary: '付款条款（归纳，写入起诉状）',
  retention_ratio: '质保金比例',
  payable_ratio: '应付至合同款比例',
  jurisdiction_text: '管辖段落',
  contract_party_b: '合同乙方（盖章页）',
  elevator_qty_contract: '台数（约定，写入起诉状）',
  elevator_qty_vge: 'VGE 家用电梯台数',
  handover_text: '移交 / 结算表述',
  retention_clause_text: '质保金条款',
  retention_unpaid_amount: '审批表未付质保金',
  document_kind: '文书类型',
  arbitration_institution: '仲裁机构',
  addressee: '致送（法院 / 仲裁委）',
};

/** 审核表格中展示的字段（有序） */
export const reviewFieldKeys: string[] = [
  'plaintiff_name_final',
  'plaintiff_credit_code',
  'plaintiff_person_in_charge',
  'plaintiff_address',
  'plaintiff_phone',
  'defendant_name',
  'defendant_credit_code',
  'defendant_legal_rep',
  'defendant_address',
  'contacts',
  'contract_no',
  'contract_title',
  'document_kind',
  'contract_type',
  'contract_party_b',
  'contract_sign_date',
  'elevator_qty_contract',
  'elevator_qty',
  'elevator_qty_vge',
  'total_amount',
  'paid_amount',
  'unpaid_amount',
  'acceptance_latest_date',
  'retention_ratio',
  'retention_clause_text',
  'retention_unpaid_amount',
  'payable_ratio',
  'handover_text',
  'payment_clause_location',
  'payment_clause_summary',
  'payment_clause_text',
  'breach_interest_rate_text',
  'interest_rate_basis',
  'dispute_clause_location',
  'dispute_clause_text',
  'project_site',
  'court_district',
  'jurisdiction_text',
  'arbitration_institution',
  'addressee',
];
